name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
      - run: flutter create --project-name tip_calc .
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: nightly
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
